package com.heapanalyzer.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

/**
 * Integrates with OpenAI via Spring AI to interpret
 * static analysis reports and produce actionable recommendations.
 */
@Service
public class SpringAiService {

    private static final Logger log = LoggerFactory.getLogger(SpringAiService.class);

    private final ChatClient chatClient;

    private static final String SYSTEM_PROMPT = """
            You are an expert Java Performance Engineer with deep expertise in JVM internals,
            garbage collection, and memory management. You are analyzing a static heap dump report
            generated by Eclipse Memory Analyzer (MAT).

            Your task:
            1. Summarize the root cause of the memory issue in plain language.
            2. Identify the exact classes, threads, or data structures that are retaining the most memory.
            3. Explain WHY this is problematic (e.g., unbounded cache, leaked connection, classloader leak).
            4. Provide **actionable, code-level recommendations** to fix the issue.
            5. If applicable, suggest JVM tuning flags that could mitigate the impact.

            Format your response in clean Markdown with headers, bullet points, and code blocks where appropriate.
            """;

    public SpringAiService(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Sends the static analysis report to OpenAI and returns the AI's interpretation.
     */
    public String analyze(String staticReport) {
        log.info("Sending static analysis report to OpenAI ({} chars)...", staticReport.length());

        String response = chatClient.prompt()
                .system(SYSTEM_PROMPT)
                .user(staticReport)
                .call()
                .content();

        log.info("Received AI response ({} chars)", response != null ? response.length() : 0);
        return response;
    }
}
