package com.heapanalyzer.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

/**
 * Integrates with OpenAI via Spring AI to interpret
 * static analysis reports and produce actionable recommendations.
 * Supports heap dump, thread dump, and GC log analysis.
 */
@Service
public class SpringAiService {

    private static final Logger log = LoggerFactory.getLogger(SpringAiService.class);

    private final ChatClient chatClient;

    private static final String HEAP_DUMP_PROMPT = """
            You are an expert Java Performance Engineer with deep expertise in JVM internals,
            garbage collection, and memory management. You are analyzing a static heap dump report
            generated by Eclipse Memory Analyzer (MAT).

            Your task:
            1. Summarize the root cause of the memory issue in plain language.
            2. Identify the exact classes, threads, or data structures that are retaining the most memory.
            3. Explain WHY this is problematic (e.g., unbounded cache, leaked connection, classloader leak).
            4. Provide **actionable, code-level recommendations** to fix the issue.
            5. If applicable, suggest JVM tuning flags that could mitigate the impact.

            Format your response in clean Markdown with headers, bullet points, and code blocks where appropriate.
            """;

    private static final String THREAD_DUMP_PROMPT = """
            You are an expert Java Performance Engineer specializing in concurrency,
            thread management, and JVM diagnostics. You are analyzing a JVM thread dump.

            Your task:
            1. **Executive Summary** — Summarize the overall health of the application's threading in 2-3 sentences.
            2. **Thread State Analysis** — Analyze the distribution of thread states (RUNNABLE, WAITING, BLOCKED, TIMED_WAITING) and what it reveals about the application behavior.
            3. **Deadlock Detection** — If deadlocks are present, explain the deadlock chain clearly and identify the root cause.
            4. **Bottleneck Identification** — Identify any thread contention, lock contention, or resource bottlenecks. Look for:
               - Multiple threads blocked on the same lock
               - Thread pool exhaustion
               - Database connection pool starvation
               - Excessive thread creation
            5. **Suspicious Patterns** — Flag any concerning patterns like:
               - Threads stuck in I/O operations
               - Long-running GC threads blocking application threads
               - Threads waiting on external services (HTTP calls, database queries)
            6. **Actionable Recommendations** — Provide specific, code-level fixes including:
               - Lock ordering changes to prevent deadlocks
               - Thread pool configuration tuning
               - Connection pool sizing recommendations
               - Code patterns to reduce contention

            Format your response in clean Markdown with headers, bullet points, and code blocks where appropriate.
            """;

    private static final String GC_LOG_PROMPT = """
            You are an expert Java Performance Engineer specializing in JVM garbage collection
            tuning and memory management. You are analyzing a JVM GC log.

            Your task:
            1. **Executive Summary** — Summarize the GC behavior and overall memory health in 2-3 sentences.
            2. **GC Performance Analysis** — Analyze pause times, frequency, and distribution:
               - Are pause times acceptable for the application type?
               - Is there a trend of increasing pause times?
               - What percentage of time is spent in GC vs. application work?
            3. **Memory Pressure Assessment** — Evaluate heap usage patterns:
               - Is the heap properly sized?
               - Is there evidence of a memory leak (increasing baseline after GC)?
               - Are there humongous allocations (G1GC)?
               - Is promotion rate healthy?
            4. **Full GC Analysis** — If Full GCs are present:
               - What triggers them?
               - How can they be reduced or eliminated?
            5. **Collector-Specific Recommendations** — Based on the detected collector:
               - Is it the right collector for this workload?
               - Specific tuning flags and their recommended values
            6. **Actionable Recommendations** — Provide specific JVM flags and code changes:
               - Heap sizing (-Xms, -Xmx)
               - GC tuning parameters
               - Application-level changes to reduce GC pressure
               - Consider alternative collectors if appropriate

            Format your response in clean Markdown with headers, bullet points, and code blocks where appropriate.
            """;

    public SpringAiService(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Sends a heap dump static analysis report to AI for interpretation.
     */
    public String analyze(String staticReport) {
        return sendToAi(HEAP_DUMP_PROMPT, staticReport, "heap dump");
    }

    /**
     * Sends a thread dump analysis report to AI for interpretation.
     */
    public String analyzeThreadDump(String threadDumpReport) {
        return sendToAi(THREAD_DUMP_PROMPT, threadDumpReport, "thread dump");
    }

    /**
     * Sends a GC log analysis report to AI for interpretation.
     */
    public String analyzeGcLog(String gcLogReport) {
        return sendToAi(GC_LOG_PROMPT, gcLogReport, "GC log");
    }

    private String sendToAi(String systemPrompt, String content, String type) {
        log.info("Sending {} report to AI ({} chars)...", type, content.length());

        String response = chatClient.prompt()
                .system(systemPrompt)
                .user(content)
                .call()
                .content();

        log.info("Received AI response for {} ({} chars)", type, response != null ? response.length() : 0);
        return response;
    }
}
