package com.heapanalyzer.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Parses JVM thread dump files and extracts structured statistics
 * for AI consumption.
 *
 * <p>Supports thread dumps generated by {@code jstack}, {@code jcmd Thread.print},
 * and {@code kill -3} signal.</p>
 */
@Service
public class ThreadDumpAnalysisService {

    private static final Logger log = LoggerFactory.getLogger(ThreadDumpAnalysisService.class);

    /** Max characters to send to the LLM */
    private static final int MAX_REPORT_CHARS = 30_000;

    private static final Pattern THREAD_NAME_PATTERN =
            Pattern.compile("^\"(.+?)\".*");

    private static final Pattern THREAD_STATE_PATTERN =
            Pattern.compile("\\s+java\\.lang\\.Thread\\.State:\\s+(\\S+)");

    private static final Pattern DEADLOCK_PATTERN =
            Pattern.compile("Found (one|\\d+) Java-level deadlock", Pattern.CASE_INSENSITIVE);

    /**
     * Parses the thread dump file and produces a structured summary.
     */
    public String analyze(Path threadDumpPath) throws IOException {
        String content = Files.readString(threadDumpPath, StandardCharsets.UTF_8);
        log.info("Parsing thread dump: {} ({} chars)", threadDumpPath.getFileName(), content.length());

        StringBuilder report = new StringBuilder();
        report.append("Thread Dump Analysis Report\n");
        report.append("=".repeat(60)).append("\n\n");

        // Thread state counts
        Map<String, Integer> stateCounts = new LinkedHashMap<>();
        stateCounts.put("RUNNABLE", 0);
        stateCounts.put("WAITING", 0);
        stateCounts.put("TIMED_WAITING", 0);
        stateCounts.put("BLOCKED", 0);
        stateCounts.put("NEW", 0);
        stateCounts.put("TERMINATED", 0);

        // Parse threads
        List<String> blockedThreads = new ArrayList<>();
        List<String> runnableThreads = new ArrayList<>();
        int totalThreads = 0;
        boolean hasDeadlock = false;
        StringBuilder deadlockSection = new StringBuilder();

        String[] lines = content.split("\n");
        String currentThreadName = null;
        String currentState = null;
        boolean inDeadlockSection = false;

        for (int i = 0; i < lines.length; i++) {
            String line = lines[i];

            // Detect deadlock section
            Matcher deadlockMatcher = DEADLOCK_PATTERN.matcher(line);
            if (deadlockMatcher.find()) {
                hasDeadlock = true;
                inDeadlockSection = true;
                deadlockSection.append(line).append("\n");
                continue;
            }

            if (inDeadlockSection) {
                deadlockSection.append(line).append("\n");
                if (line.trim().isEmpty() && i + 1 < lines.length
                        && !lines[i + 1].trim().startsWith("\"")
                        && !lines[i + 1].contains("waiting to lock")
                        && !lines[i + 1].contains("which is held by")) {
                    inDeadlockSection = false;
                }
                continue;
            }

            // Match thread header
            Matcher nameMatcher = THREAD_NAME_PATTERN.matcher(line);
            if (nameMatcher.matches()) {
                currentThreadName = nameMatcher.group(1);
                totalThreads++;
                currentState = null;
            }

            // Match thread state
            Matcher stateMatcher = THREAD_STATE_PATTERN.matcher(line);
            if (stateMatcher.find()) {
                currentState = stateMatcher.group(1);
                stateCounts.merge(currentState, 1, Integer::sum);

                if ("BLOCKED".equals(currentState) && currentThreadName != null) {
                    blockedThreads.add(currentThreadName);
                }
                if ("RUNNABLE".equals(currentState) && currentThreadName != null) {
                    runnableThreads.add(currentThreadName);
                }
            }
        }

        // Summary
        report.append("## Thread Summary\n\n");
        report.append(String.format("Total threads found: %d\n\n", totalThreads));

        report.append("### Thread State Distribution\n\n");
        for (var entry : stateCounts.entrySet()) {
            if (entry.getValue() > 0) {
                double pct = totalThreads > 0 ? (entry.getValue() * 100.0 / totalThreads) : 0;
                report.append(String.format("  %-15s : %4d  (%.1f%%)\n",
                        entry.getKey(), entry.getValue(), pct));
            }
        }
        report.append("\n");

        // Deadlock info
        if (hasDeadlock) {
            report.append("### ⚠️ DEADLOCK DETECTED\n\n");
            report.append(deadlockSection).append("\n");
        } else {
            report.append("### Deadlock Check: No deadlocks detected\n\n");
        }

        // Blocked threads
        if (!blockedThreads.isEmpty()) {
            report.append("### Blocked Threads (").append(blockedThreads.size()).append(")\n\n");
            for (String t : blockedThreads) {
                report.append("  - ").append(t).append("\n");
            }
            report.append("\n");
        }

        // Top runnable threads
        if (!runnableThreads.isEmpty()) {
            report.append("### Active Runnable Threads (top 20)\n\n");
            runnableThreads.stream().limit(20).forEach(t ->
                    report.append("  - ").append(t).append("\n"));
            report.append("\n");
        }

        // Append raw content (truncated) for AI context
        report.append("## Raw Thread Dump (for detailed analysis)\n\n");
        report.append("```\n");

        String rawSection = content;
        int remainingChars = MAX_REPORT_CHARS - report.length() - 100;
        if (rawSection.length() > remainingChars && remainingChars > 0) {
            rawSection = rawSection.substring(0, remainingChars)
                    + "\n\n[... THREAD DUMP TRUNCATED ...]";
        }
        report.append(rawSection);
        report.append("\n```\n");

        String result = report.toString();
        log.info("Thread dump analysis complete: {} threads found, deadlock={}, {} chars",
                totalThreads, hasDeadlock, result.length());
        return result;
    }
}
